# Generated by Django 6.0.6 on 2026-06-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.CharField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.CharField(blank=True, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram_url',
            field=models.CharField(blank=True, null=True, verbose_name='لینک تلگرام'),
        ),
    ]
