# Generated by Django 6.0.6 on 2026-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_alter_sitesetting_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_super_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن اصلی درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_us_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن تیتر تماس با ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_slogan',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='شعار سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن تیتر درباره ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copy_right',
            field=models.TextField(blank=True, null=True, verbose_name='متن کپی رایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='is_main_setting',
            field=models.BooleanField(default=False, max_length=250, verbose_name='تنظیمات اصلی'),
        ),
    ]
