# Generated by Django 6.0.6 on 2026-06-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_sitesetting_about_us_super_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمات')),
                ('details', models.TextField(verbose_name='متن خدمات')),
                ('image', models.ImageField(upload_to='images/site-services/', verbose_name='تصویر خدمات')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_config.sitesetting')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات سایت',
            },
        ),
    ]
