# Generated by Django 6.0.6 on 2026-06-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_siteservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.CharField(blank=True, null=True, verbose_name='توضیحات')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_config.sitesetting')),
            ],
            options={
                'verbose_name': 'بخش شبکه\u200cهای اجتماعی',
                'verbose_name_plural': ' شبکه\u200c اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaServicesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/social_media/', verbose_name='تصویر')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_config.socialmediaservices', verbose_name='گالری تصاویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
