# Generated by Django 6.0.6 on 2026-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_socialmediaservices_socialmediaservicesgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AlterField(
            model_name='socialmediaservices',
            name='massage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
    ]
