# Generated by Django 6.0.6 on 2026-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_us_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('massage', models.TextField(verbose_name='پیام کاربر')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام مشتری',
                'verbose_name_plural': 'صندوق پیام های مشتری',
            },
        ),
    ]
