# Generated by Django 6.0.6 on 2026-06-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_page', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/product_gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='Product_page.product')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
    ]
